### ISSUE TITLE
Divisible and Decidable repr

### ISSUE THREAD

**Issue by xvw** [xvw/preface#165]
Using generic product and coproducts for Divisible and Decidable is Haskell biased.
Currently we ask for `(a, b, c, d)`  to become `((a, b), c), d` for products. 
And `a | b | c` to become `((a, b) either, c) either` for coproducts. 
going for `(a, (b, c))` and `(a, (b, c) either) either` is more conveinent (and easier to write)

**Comment by xhtmlboi** [comment]
The problem is not with the implementation of `Divisible` and `Decidable` but with the precedence of `>`:

```ocaml
let f a b c = a >*< b >*< c
(* [val f : 'a t -> 'b t -> 'c t -> (('a * 'b) * c) t] *)
```
```ocaml
let g a b c = a >*< (b >*< c)
(* [val f : 'a t -> 'b t -> 'c t -> ('a * ('b * c)) t] *)
```
You can use, for example, `@>*<` but it break the symetry with applicative... or `^*^` which seems  better: 

```ocaml
let h a b c = a ^*^ b ^*^ c
(* [val f : 'a t -> 'b t -> 'c t -> ('a * ('b * c)) t] *)
```

(But I suggest to add `^$^`: `let i f a b c d = f ^$^ a ^*^ b ^*^ c ^*^ d` has the expected type and you do not need extra parentheses between the Divisible part.)
